project_id = "cxiudqwfwpdwpfyqpaxw"

[functions.google-auth-start]
verify_jwt = true

[functions.google-auth-callback]
verify_jwt = false

[functions.get-sheet-headers]
verify_jwt = true

[functions.sync-sheet]
verify_jwt = true

[functions.get-public-sheet-headers]
verify_jwt = false

[functions.sync-public-sheet]
verify_jwt = true

[functions.auto-sync]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false
